# Generated by Django 6.0.6 on 2026-06-09 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('dimension', models.IntegerField()),
                ('desbloqueado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('id_subtema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_subtema', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PalabraDesafio',
            fields=[
                ('id_palabra', models.AutoField(primary_key=True, serialize=False)),
                ('palabra', models.CharField(max_length=50)),
                ('pista', models.TextField()),
                ('id_subtema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subtema')),
            ],
            options={
                'unique_together': {('id_subtema', 'palabra')},
            },
        ),
        migrations.CreateModel(
            name='NivelProgresion',
            fields=[
                ('id_nivel_prog', models.AutoField(primary_key=True, serialize=False)),
                ('id_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nivel')),
                ('id_subtema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subtema')),
            ],
            options={
                'unique_together': {('id_nivel', 'id_subtema')},
            },
        ),
    ]
