# Generated by Django 3.2.25 on 2026-05-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=100, verbose_name='ID o Número del Nivel')),
                ('pregunta', models.TextField()),
                ('palabra', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('dimension', models.IntegerField(default=15)),
                ('desbloqueado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
